# Generated by Django 6.0.4 on 2026-04-22 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('tech', 'Technology'), ('music', 'Music'), ('art', 'Art & Design'), ('language', 'Language'), ('tutoring', 'Tutoring'), ('fitness', 'Fitness'), ('cooking', 'Cooking'), ('other', 'Other')], default='other', max_length=20)),
                ('is_free', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank if free', max_digits=8, null=True)),
                ('contact_preference', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('in_app', 'In-App Message')], default='email', max_length=20)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy — Limited Slots'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
